database:
  protocol: postgres
  user: postgres
  password: mysecretpassword
  host: localhost
  port: 5432
  database: iot-orchid
api:
  debug:
    host: 0.0.0.0
    port: 3001
  production:
    host: 0.0.0.0
    port: 3001
jwt:
  secret: mysecret
  access_expires_in: 86400
  refresh_expires_in: 604800
  issuer: iot-orchid
  microdevice:
    secret: mysecret
    expires_in: 2700
    issuer: iot-orchid
ampq:
  host: localhost
  port: 5672
  user: guest
  password: guest
  mqtt_gateway_queue_name: mqtt-gateway-wq
  telemetry_queue_name: telemetry-wq
  registrar_queue_name: registrar-wq
  timeout: 120
port: 3001
address: 0.0.0.0
