//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cluster")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::microdevice::Entity")]
    Microdevice,
    #[sea_orm(has_many = "super::user_cluster::Entity")]
    UserCluster,
}

impl Related<super::microdevice::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Microdevice.def()
    }
}

impl Related<super::user_cluster::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCluster.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_cluster::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_cluster::Relation::Cluster.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
