//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub password_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_cluster::Entity")]
    UserCluster,
}

impl Related<super::user_cluster::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCluster.def()
    }
}

impl Related<super::cluster::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_cluster::Relation::Cluster.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_cluster::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
